id: P008095
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6900
  title: འཚོ་བའི་རྒྱུན་ཤེས་མུ་ཏིག་དོ་ཤལ།
  author: ''
  volumes:
    d0573cba12854303a7bd2103ee675af2:
      image_group_id: I3CN6902
      title: ''
      volume_number: 1
      total_pages: 180
ebook_metadata:
  title: འཚོ་བའི་རྒྱུན་ཤེས་མུ་ཏིག་དོ་ཤལ།
  author: ''
  sku: P008095
  cover: cover.jpg
  layers:
  - pagination
