id: P008095
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6900
  title: འཚོ་བའི་རྒྱུན་ཤེས་མུ་ཏིག་དོ་ཤལ།
  author: ''
  volumes:
    0dd898686cfa4a36b3960db0470f0008:
      image_group_id: I3CN6902
      title: Volume 1 of 'tsho ba'i rgyun shes mu tig do shal/
      volume_number: 1
      total_pages: 180
      base_file: v001.txt
